SELECT 
  CU.CHR_CUENCODIGO CUENTA,
  CU.CHR_SUCUCODIGO SUCURSAL,
  CL.VCH_CLIEPATERNO || ' ' ||
  CL.VCH_CLIEMATERNO || ', ' ||
  CL.VCH_CLIENOMBRE CLIENTE,
  M.VCH_MONEDESCRIPCION MONEDA,
  CU.DEC_CUENSALDO SALDO,
  CU.DTT_CUENFECHACREACION FECHA,
  CU.VCH_CUENESTADO ESTADO,
  CU.INT_CUENCONTMOV MOVS
FROM MONEDA M
JOIN CUENTA CU ON M.CHR_MONECODIGO = CU.CHR_MONECODIGO
JOIN CLIENTE CL ON CU.CHR_CLIECODIGO = CL.CHR_CLIECODIGO
WHERE CU.CHR_CUENCODIGO = '00200002';


SELECT
   SUCUCODIGO,
   SUCUNOMBRE,
   CLIECODIGO,
   CLIENOMBRE,
   CUENCODIGO,
   CUENSALDO,
   CUENESTADO,
   MOVINUMERO,
   MOVIFECHA,
   MOVIIMPORTE,
   CUENREFERENCIA,
   TIPOCODIGO,
   TIPONOMBRE,
   TIPOACCION,
   MONECODIGO,
   MONENOMBRE
FROM V_MOVIMIENTO
WHERE CUENCODIGO = '00200002';




 
 